### ISSUE TITLE
Create prediction tool - Replace setup & teardown days with calendar event selectors

### ISSUE THREAD

**Issue by DarkmatterVale** [Enercast-Solutions/website#9]
Additionally, some logic will need to be added to automatically calculate durations for the API call that is executed on submit. You cannot simply submit dates to the API for setup/teardown.

Due date: 4/9/21

**Comment by jackyruanjunzhe** [comment]
For this one, do you mean I should calculate the event days between the start date and end date? If yes, where do you want me to store them? Why can't we submit the dates to the API? Can the backend(DPA) team directly deal with the start date and end date? And what do you mean by automatically calculate durations for the API?

**Comment by DarkmatterVale** [comment]
Currently, users input the number of days that will be required for setup / teardown. Instead, they should specify a start and end date in which setup is completed, and a start an end date in which tear down is completed.

Internally, we do not want to submit the dates themselves back to the API. Instead, calculate the duration of setup and teardown using the date ranges provided by the user, and submit only the number of days to the back-end API.

When we display data to users in the previous prediction pages, we can simply display the number of setup and teardown days, instead of trying to display the date ranges. This is simpler.
